import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: user } = useSession();

  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World</h1>

        <div className="mt-5 flex space-x-3 text-blue-500">
          <Link href="/login">Login</Link>
          <Link href="/register">Register</Link>
        </div>
      </main>
    </>
  );
};

export default Home;
