import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/Header";
import Layout from "~/components/Layout";
import Notes from "~/components/note/Notes";
import Topics from "~/components/topic/Topics";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fullstack T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Layout>
          <Topics />
          <Notes />
        </Layout>
      </main>
    </>
  );
};

export default Home;
