import { type NextPage } from "next";
import Head from "next/head";
import PostForm from "~/components/PostForm";
import Layout from "~/layout/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <PostForm />
      </Layout>
    </>
  );
};

export default Home;
